---
- name: copy file from one server to another server
  hosts: all
  become: yes

  tasks:
   - name: Copy file with owner and permissions
     ansible.builtin.copy:
       src: /home/ec2-user/akhil
       dest: /home/ec2-user/ansible/akhil
       owner: ec2-user
       group: ec2-user
       mode: '0644'
       remote_src: True
