---
- name: install mq
  hosts: all
  become: yes
  vars:
    path: /home/mqm/bin
    path1: /home/MQServer
  
  tasks : 
    - name: create users 
      ansible.builtin.user:
        name: mqm
        

  #  - name: download the package
  #    ansible.builtin.get_url:
  #     url: https://drive.google.com/file/d/1-ovWCIuD06bDgGxoxssge4Q4aCgECovg/view?usp=drive_link
  #      dest: /home

    - name: extract the file 
      ansible.builtin.unarchive:
       src: /home/IBM_MQ.tar.gz
       dest: /home/
       remote_src: yes    

    - name: Updating sysctl.con  file
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        regexp: '^kernel.shmmni = 4096'
        line: kernel.shmmni = 4096
        regexp : '^kernel.shmall = 1073741824'
        line : kernel.shmall = 2097152
        regexp : '^kernel.shmmax = 4398046511104'
        line : kernel.shmmax = 268435456
        regexp : '^kernel.sem = 250 32000 100 128'
        line : kernel.sem = 500 256000 250 1024

    - name: update file with limits
      ansible.builtin.blockinfile:
        path: /etc/security/limits.conf
        block: |
           mqm  hard  nproc  4096
           mqm  soft  nproc  4096
           mqm  hard  nofile 10240
           mqm  soft  nofile 10240

    - name: accept licence 
      ansible.builtin.shell: '{{ path1 }}/mqlicense.sh -accept'

# Get a list of rpms from a directory
    - name: find rpm files and register the result 
      find:
        paths: /home/MQServer
        patterns: "*.rpm"
      register: rpm_files

# Create a list of the rpms to use with the yum install command
    - set_fact:
       rpm_list: "{{ rpm_files.files | map(attribute='path') | list}}"

# Use yum to install with a list
    - name: install rpm files using rpm_list
      community.general.apt_rpm:
          pkg: "{{ rpm_list }}"
          state: present
      become: yes    
      become_method: sudo

    - name : to set instance 
      command : '.{{ path }}/setmqinst -i -p /home/mqm'

    - name : check package is installed or not
      command : '.{{ path }}/mqconfig'
