---
- name: copy file from one server to another server
  hosts: 192.168.1.44
  become: yes

  tasks:
   - name: create users 
     user:
        name: "{{ item.user }}"
        password: "{{ item.password }}"
        state: present
     with_items:
          - { user: ansible-agent, password: 1254254125 }
          - { user: agent, password: 252545 }  
      
   - name: Insert/Update "Match User" configuration block in /etc/ssh/sshd_config
     ansible.builtin.blockinfile:
         path: /etc/ssh/sshd_config
         block: |
               Match User ansible-agent
               PasswordAuthentication no